### ISSUE TITLE
Clojure.g4 attribution

### ISSUE THREAD

**Issue by arrdem** [venantius/glow#11]
Hey @venantius,

I was auditing your project for alternatives to pygments for highlighting Clojure, and took a look at [resources/parsers/Clojure.g4](https://github.com/venantius/glow/blob/master/resources/parsers/Clojure.g4). It looked pretty familiar as I scrolled down it, and I was honestly shocked to recognize some "FIXME" comments I remembered writing.

I'd appreciate it if you'd at least mention me and the other authors of that grammar. The MIT license does require attribution.

Thanks.

**Comment by venantius** [comment]
Hey @arrdem - I'm very sorry about that. I've pushed up a new commit with proper attribution: https://github.com/venantius/glow/commit/18f8132659f124d025e0f5f5910992c2fc4fdb79. Thank you for your work on this.
