### ISSUE TITLE
HTML output?

### ISSUE THREAD

**Issue by emil0r** [venantius/glow#4]
Would it be possible to add HTML output?

**Comment by venantius** [comment]
It's definitely possible. I'm curious what use case you have in mind that wouldn't be satisfied by, say, using highlight.js or an equivalent JS library.

**Comment by emil0r** [comment]
End result would be the same, but I wish to avoid an additional dependancy on the webpage and additional loading cost as the library parses the code.

**Comment by venantius** [comment]
The path that this project is moving in, just FYI, is one that ends up with a hiccup-style parse tree as an intermediate processing step before collapsing that tree into a syntax-highlighted string. This means that one should be able to generate HTML for it by, e.g., applying an Instaparse transformation to it to apply whatever styles you might want before passing it to the hiccup rendering engine.

**Comment by venantius** [comment]
This has now been asked for 3 times by different people in different forums so unless you're just sock-puppetting me I'm going to put this on the roadmap for Glow.

**Comment by vincentstorme** [comment]
:+1:

**Comment by venantius** [comment]
If you're interested, there's an open PR here https://github.com/venantius/glow/pull/8 that includes  HTML / CSS output generation functions. If that works for you I'll probably cut a release this weekend.

**Comment by emil0r** [comment]
I'll play around with it a bit, but one thing I notice when looking at it is that it very much correctly spits out HTML.

However... spitting out a hiccup style data structure might be preferred so that those who choose to use something other than hiccup can still parse it out as HTML. Enlive for example can do that, although you need to be a bit careful with the attributes as it doesn't play nice with keywords (think {:class :my-css-class} vs {:class "my-css-class"}).

Personally hiccup doesn't inconvenience as that is what I use in my current project anyway. But I thought I'd leave this comment as food for thought.

Cheers :)

**Comment by venantius** [comment]
Yeah, `glow.html/hiccup-transform` will transform a parse tree into a hiccup data tree, but I could also build a transformer for enlive or something like that. I'm sure there already exists a hiccup-to-enlive translator somewhere else though if people need it.

**Comment by venantius** [comment]
Resolved.
